name: inaeats
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^5.0.0
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1 
  equatable: ^2.0.7
  flutter_svg: ^2.1.0
  get_it: ^8.0.3
  intl: ^0.20.2
  pretty_dio_logger: ^1.4.0
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  google_maps_flutter: ^2.12.3
  flutter_bloc: ^9.1.1
  fluttertoast: ^8.2.12
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  flutter_slidable: ^4.0.0
  collection: ^1.19.1
  youtube_player_flutter: ^9.1.1
  flutter_dotenv: ^5.2.1
  location: ^8.0.1
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  flutter_polyline_points: ^2.1.0
  http: ^1.4.0
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.5.3
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/gifs/
    - assets/data/product.data
    - assets/.env

  fonts:
    - family: AlbertSans
      fonts:
        - asset: assets/fonts/AlbertSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/AlbertSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/AlbertSans-Light.ttf
          weight: 300
        - asset: assets/fonts/AlbertSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/AlbertSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/AlbertSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/AlbertSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/AlbertSans-ExtraBold.ttf
          weight: 800
  
